name: Import Feed Items
on:
    workflow_dispatch: {}
    schedule:
        - cron: '0 0 * * *'
    push:
        branches:
            - main

jobs:
    Import-Feed-Items:
        name: Import Feed Items
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Import feeds
              run: npm run import-feeds
              env:
                  SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
                  SANITY_DATASET: ${{ secrets.SANITY_DATASET }}

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  commit-message: Imported feed items
                  branch: import-feed-items-update-${{ github.run_number }}
                  title: 'Import Feed Items'
                  body: 'This PR imports feed items and updates the content.'
                  labels: 'automated pr'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
